version: '3'
services:
  spring-boot:
    image: springci/spring-boot-ci-image
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - spring.env
    volumes:
      - ./:/usr/src/maven
    depends_on:
      - "database"
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: