spring:
  server:
    port: 8080
    # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/db
    username: admin
    password: admin
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
openweather:
  appid: "5f701b8da7b37714d9898d9f430cc68c"
  apipath: "http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appid}"