spring:
  profiles:
    default: dev
    active: ${SPRING_ACTIVE_PROFILE}
  h2:
    console:
      enabled: true
      path: /h2
  server:
    port: 8080
openweather:
  appid: "5f701b8da7b37714d9898d9f430cc68c"
  apipath: "http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appid}"